Database
readme-experts/cyberchef pull request #28
Opened 2021-12-30 14:41 UTC by ILabiak

Wrote code to connect to database and to insert recipes, user data, categories and user favourite recipes. Also used parametrized queries to avoid sql injection

2021-12-30 21:18 UTC, akaeyuhi requested changes
Some minor fixes needed

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/config/confix-example.json
> +{
You can use dotenv module and .env file for storing configs

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/db.js
> +let con;
You can return connection as a result of calling this function, but ok

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/db.js
> +  if (checkUserExistence[0]) return 'User with this username already exists';
throw error here

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/db.js
> +  if (checkMailExistence[0]) return 'User with this email already exists';
and here

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/db.js
> +  }).then();
You can replace then() with await i quess

2021-12-30 21:18 UTC, akaeyuhi commented on src/database/db.js
> +  }).then();
return await new Promise...

2021-12-31 12:40 UTC, ILabiak commented
> 

Refactored code

2022-01-01 23:52 UTC, akaeyuhi approved these changes

2022-01-01 23:52 UTC, merged