Api
readme-experts/cyberchef pull request #29
Opened 2022-01-04 21:20 UTC by water-korra

2022-01-04 21:35 UTC, akaeyuhi requested changes
Huge code style problems

2022-01-04 21:35 UTC, akaeyuhi commented on .eslintrc.json
> -{
zachem

2022-01-04 21:35 UTC, akaeyuhi commented on .prettierrc
> -{
zachem x2

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/Controller.js
> +const db = require('../database/db')
Use prettier pls

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/Controller.js
> +            res.status(400).json({message: 'error by getting recipe by id'});
If you are using express.json middleware .json is redundant

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/authController.js
> +              // const candidate = db.getUserData(username)
Delete commented lines

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/authController.js
> +            const user =  await db.getUserData(username)
Prettier

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/authController.js
> +            console.log(e)
Delete console.log() here and further

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/authController.js
> +            console.log(e)
Using log for error is a bad practice

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/authconfig.js
> +    secret: "keykey"
Generate random secret on production

2022-01-04 21:35 UTC, akaeyuhi commented on src/api/package.json
> +    "mongoose": "^6.1.4",
Unysed dependencies

2022-01-04 21:35 UTC, akaeyuhi commented on src/database/db.js
> +  return undefined;
Dont return undefined, it`s returned by default

2022-01-04 21:35 UTC, akaeyuhi commented on src/database/db.js
> +  return undefined;
and here

2022-01-04 21:35 UTC, akaeyuhi commented on src/database/db.js
> +  return undefined;
and here

2022-01-05 23:33 UTC, akaeyuhi reviewed
Delete DS store files

2022-01-06 14:50 UTC, akaeyuhi requested changes
Still a lot of things to refactor here

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/controllers/Controller.js
> +      const user_id = tokenService.getUserId(req);
camelcase pls

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/controllers/Controller.js
> +      for (let i = 0; i < userFavId.length; i++) {
for of would be better

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/controllers/Controller.js
> +ParseService.addRecipesFromParcer(jsonData)
Is this a class of smth?

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/controllers/authController.js
> +class authController {
Name classes with capital letter

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/service/recipe-service.js
> +    addRecipesFromParcer = (jsonData) => {
Arrow function in a class is weird

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/service/recipe-service.js
> +        for(let i = 0;i<jsonData.length;i++){
code style and for of

2022-01-06 14:50 UTC, akaeyuhi commented on src/api/service/recipe-service.js
> +            db.addRecipeToDb(name,category_id,products,description,image_link)
You don`t need a whole class just to create an alias for db api function

2022-01-06 14:50 UTC, akaeyuhi commented on src/database/db.js
> +  return undefined;
Undefined once again

2022-01-06 14:50 UTC, akaeyuhi commented on src/database/db.js
> +  const CategoryNameRequest = `SELECT name FROM categories WHERE id = ?`;
Capital letter and not a class

2022-01-06 14:50 UTC, akaeyuhi commented on src/database/db.js
> +  return undefined;
And again

2022-01-06 20:20 UTC, akaeyuhi commented on src/api/controllers/Controller.js
> +// let jsonData = require('../../parser/recipes.json');
ирина *б твою мть

2022-01-06 20:20 UTC, akaeyuhi commented on src/api/routes/authRouter.js
> +
ок

2022-01-06 20:22 UTC, akaeyuhi requested changes
Vesma neudovletvoritelno, zaimetes` ulutscheniem

2022-01-07 14:00 UTC, water-korra commented on src/api/service/recipe-service.js
> +    addRecipesFromParcer = (jsonData) => {
fixed cap

2022-01-08 22:25 UTC, akaeyuhi commented on src/api/controllers/authController.js
> +      const { username, email, password } = req.body;
better to check body to not get undefined but ok

2022-01-08 22:26 UTC, akaeyuhi approved these changes

2022-01-08 22:27 UTC, merged