Parser
readme-experts/cyberchef pull request #30
Opened 2022-01-06 11:41 UTC by MrPaschenko

Closes #5

2022-01-06 14:42 UTC, akaeyuhi requested changes
Use camelcase, decompose main function

2022-01-06 14:42 UTC, akaeyuhi commented on src/parser/index.js
> +// const chalk = require('chalk');
Delete commented lines pls

2022-01-06 14:42 UTC, akaeyuhi commented on src/parser/index.js
> +      // eslint-disable-next-line camelcase
Disabled eslint

2022-01-06 14:42 UTC, akaeyuhi commented on src/parser/index.js
> +      const category_id = $1('.article-breadcrumbs')
Use camelcase for variables

2022-01-06 14:42 UTC, akaeyuhi commented on src/parser/index.js
> +(async function main() {
Big undecomposed function

2022-01-06 15:07 UTC, MrPaschenko commented on src/parser/index.js
> +      const category_id = $1('.article-breadcrumbs')
`snake_case` is required from db team

2022-01-06 15:08 UTC, MrPaschenko commented on src/parser/index.js
> +      // eslint-disable-next-line camelcase
Used for `camel_case`

2022-01-06 15:09 UTC, MrPaschenko commented on src/parser/index.js
> +// const chalk = require('chalk');
Done

2022-01-08 15:05 UTC, yanu1ya commented
пітца

2022-01-08 22:24 UTC, akaeyuhi approved these changes

2022-01-08 22:27 UTC, merged